### Check fiscal code
POST http://localhost:57156/api/cfCheck
Content-Type: application/json

{
    "fiscalCode": "MRZMNL79E68H501Z",
    "firstName": "Manuele",
    "lastName": "Marzotti",
    "birthDate": "1979-05-28T00:00:00.000Z",
    "pin": ""
}

### Store application without pin
POST http://localhost:57156/api/application
Content-Type: application/json

{
    "fiscalCode": "MRZMNL79E68H501Z",
    "firstName": "Manuele",
    "lastName": "Marzotti",
    "birthDate": "1979-05-28T00:00:00.000Z",
    "email": "manuele.marzotti@pippo.it",
    "phoneNumber": "+393331234567",
    "workingDays": 101,
    "drivingLicense": "C class - issued on 10/11/2010 - valid until 10/11/2020",
	"businessUnits": [ "BU1", "BU2", "BU3" ],
    "pin": null
}

### Get statistics
GET http://localhost:57156/api/statistics

### Get application page
GET http://localhost:57156/api/application?startIndex=0&howMany=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOiIxNTI4NTc0MTcyIiwidXNlcm5hbWUiOiJmb28ifQ.Qi18JsuMTtYRltqL_p3W1wY1MbrJwy5AW9G65OC3SdE

### Get in-error application page
GET http://localhost:57156/api/application?startIndex=0&howMany=10&onlyErrors=true

### Get application page
GET http://localhost:57156/api/application?id=ABCD

### Authentication
POST http://localhost:57156/api/auth
Content-Type: application/json

{
  "username": "foo",
  "password": "bar"
}